### ISSUE TITLE
Error on demo

### ISSUE THREAD

**Issue by scriptzteam** [sandrosdj/AweTracker#2]
Warning: fopen(/storage/gscp/wwwusers/29/59/tmp/2522,SOMEHASH,SOMEHASH): failed to open stream: No such file or directory in /storage/gscp/wwwusers/29/59/includes/__filtr.class.php on line 124

Warning: fwrite() expects parameter 1 to be resource, boolean given in /storage/gscp/wwwusers/29/59/includes/__filtr.class.php on line 125

Warning: fclose() expects parameter 1 to be resource, boolean given in /storage/gscp/wwwusers/29/59/includes/__filtr.class.php on line 126

**Comment by sandroshu** [comment]
Fixed /tmp location.
